// example/angular/components/app.component.ts
import { Component, Input, ViewEncapsulation } from '@angular/core';
import { CommonModule } from '@angular/common';
import { CounterComponent } from './counter.component';

@Component({
	encapsulation: ViewEncapsulation.None,
	imports: [CommonModule, CounterComponent],
	selector: 'app-root',
	standalone: true,
	styleUrl: '../../styles/app.component.css',
	templateUrl: '../templates/app.component.html'
})
export class AppComponent {
	@Input() initialCount: number = 0;
}

<main>
	<nav>
		<a href="https://absolutejs.com" target="_blank">
			<img
				class="logo"
				src="/assets/png/absolutejs-temp.png"
				alt="AbsoluteJS Logo"
			/>
		</a>
		<a href="https://angular.dev/">
			<img
				class="logo angular"
				src="/assets/svg/angular.svg"
				alt="Angular Logo"
			/>
		</a>
	</nav>
	<h1>AbsoluteJS + Angular</h1>
	<app-counter [initialCount]="initialCount"></app-counter>
	<p>
		Edit <code>example/angular/pages/angular-example.ts</code> then save and
		refresh to update the page.
	</p>
	<p style="color: #777">( Hot Module Reloading is coming soon )</p>
	<p style="margin-top: 2rem">
		Explore the other pages to see how AbsoluteJS seamlessly unifies
		multiple frameworks on a single server.
	</p>
	<p style="color: #777; font-size: 1rem; margin-top: 2rem">
		Click on the AbsoluteJS and Angular logos to learn more.
	</p>
</main>

// example/react/components/App.tsx
import { useState } from 'react';

type AppProps = { initialCount: number };

export const App = ({ initialCount }: AppProps) => {
	const [count, setCount] = useState(initialCount);

	return (
		<main>
			<nav>
				<a href="https://absolutejs.com" target="_blank">
					<img
						className="logo"
						src="/assets/png/absolutejs-temp.png"
						alt="AbsoluteJS Logo"
					/>
				</a>
				<a href="https://react.dev/">
					<img
						className="logo react"
						src="/assets/svg/react.svg"
						alt="React Logo"
					/>
				</a>
			</nav>
			<h1>AbsoluteJS + React</h1>
			<button onClick={() => setCount(count + 1)}>
				count is {count}
			</button>
			<p>
				Edit <code>example/react/pages/ReactExample.tsx</code> then save
				and refresh to update the page.
			</p>
			<p style={{ color: '#777' }}>
				( Hot Module Reloading is coming soon )
			</p>
			<p style={{ marginTop: '2rem' }}>
				Explore the other pages to see how AbsoluteJS seamlessly unifies
				multiple frameworks on a single server.
			</p>
			<p
				style={{
					color: '#777',
					fontSize: '1rem',
					marginTop: '2rem'
				}}
			>
				Click on the AbsoluteJS and HTML logos to learn more.
			</p>
		</main>
	);
};
