// example/angular/components/head.component.ts
import { Component, Input, OnChanges, SimpleChanges } from '@angular/core';
import { CommonModule } from '@angular/common';
import { DomSanitizer, SafeResourceUrl } from '@angular/platform-browser';

@Component({
	selector: 'app-head',
	standalone: true,
	imports: [CommonModule],
		template: `
		<head>
			<meta charset="UTF-8" />
			<link
				rel="icon"
				type="image/x-icon"
				href="/assets/ico/favicon.ico"
			/>
			<meta
				name="viewport"
				content="width=device-width, initial-scale=1.0"
			/>
			<title>AbsoluteJS</title>
			<link rel="stylesheet" [href]="safeCssPath" />
		</head>
	`
})
export class HeadComponent implements OnChanges {
	@Input() cssPath: string = '';
	safeCssPath: SafeResourceUrl | string = '';

	constructor(private sanitizer: DomSanitizer) {}

	ngOnChanges(changes: SimpleChanges) {
		// Sanitize the CSS path to allow it as a resource URL
		// Since we control the CSS path (from manifest), it's safe to bypass sanitization
		if (this.cssPath) {
			this.safeCssPath = this.sanitizer.bypassSecurityTrustResourceUrl(
				this.cssPath
			);
		} else {
			this.safeCssPath = '';
		}
	}
}

// example/react/components/Head.tsx
type HeadProps = {
	title?: string;
	description?: string;
	icon?: string;
	font?: string;
	cssPath?: string;
};

export const Head = ({
	title = 'AbsoluteJS + React',
	description = 'AbsoluteJS React Example',
	icon = '/assets/ico/favicon.ico',
	font = 'Poppins',
	cssPath
}: HeadProps) => (
	<head suppressHydrationWarning>
		<meta charSet="utf-8" />
		<title>{title}</title>
		<meta name="description" content={description} />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link rel="icon" href={icon} />
		<link rel="preconnect" href="https://fonts.googleapis.com" />
		<link
			rel="preconnect"
			href="https://fonts.gstatic.com"
			crossOrigin="anonymous"
			suppressHydrationWarning
		/>
		<link
			href={`https://fonts.googleapis.com/css2?family=${font}:wght@100..900&display=swap`}
			rel="stylesheet"
			suppressHydrationWarning
		/>
		{cssPath && (
			<link
				rel="stylesheet"
				href={cssPath}
				type="text/css"
				suppressHydrationWarning
			/>
		)}
	</head>
);
