// src/svelte/components/Image.svelte
<script lang="ts">
	import type { ImageProps } from '../../../types/image';
	import {
		DEFAULT_QUALITY,
		buildOptimizedUrl,
		generateBlurSvg,
		generateSrcSet
	} from '../../utils/imageProcessing';

	let {
		src,
		alt,
		width,
		height,
		fill,
		quality = DEFAULT_QUALITY,
		sizes,
		loader,
		unoptimized,
		loading,
		priority,
		placeholder,
		blurDataURL,
		className,
		style,
		onLoad,
		onError,
		crossOrigin,
		referrerPolicy,
		fetchPriority,
		overrideSrc
	}: ImageProps = $props();

	const resolvedSrc = $derived.by(() => {
		if (overrideSrc) return overrideSrc;
		if (unoptimized) return src;
		if (loader) return loader({ src, width: width ?? 0, quality });
		if (!width) return buildOptimizedUrl(src, 0, quality);
		return buildOptimizedUrl(src, width, quality);
	});

	const srcSet = $derived(
		unoptimized
			? undefined
			: generateSrcSet(src, width, sizes, undefined, loader ?? undefined)
	);

	const resolvedSizes = $derived(sizes ?? (fill ? '100vw' : undefined));

	const resolvedLoading = $derived(priority ? 'eager' : (loading ?? 'lazy'));

	const resolvedFetchPriority = $derived(priority ? 'high' : fetchPriority);

	const hasBlur = $derived(
		placeholder === 'blur' ||
			(typeof placeholder === 'string' &&
				placeholder !== 'empty' &&
				placeholder.startsWith('data:'))
	);

	const blurBackground = $derived.by(() => {
		if (!hasBlur) return undefined;
		if (
			typeof placeholder === 'string' &&
			placeholder !== 'blur' &&
			placeholder.startsWith('data:')
		) {
			return generateBlurSvg(placeholder);
		}
		if (blurDataURL) return generateBlurSvg(blurDataURL);
		return undefined;
	});

	const imgStyle = $derived.by(() => {
		const base: Record<string, string | number> = {
			...(style ?? {}),
			color: 'transparent'
		};
		if (blurBackground) {
			base.backgroundImage = blurBackground;
			base.backgroundSize = 'cover';
			base.backgroundPosition = 'center';
			base.backgroundRepeat = 'no-repeat';
		}
		if (fill) {
			base.position = 'absolute';
			base.height = '100%';
			base.width = '100%';
			base.inset = 0;
			base.objectFit = 'cover';
		}
		return Object.entries(base)
			.map(([k, v]) => `${k.replace(/[A-Z]/g, (m) => `-${m.toLowerCase()}`)}:${v}`)
			.join(';');
	});

	const handleLoad = (e: Event) => {
		if (blurBackground) {
			(e.target as HTMLImageElement).style.backgroundImage = 'none';
		}
		if (onLoad) (onLoad as (event: Event) => void)(e);
	};

	const handleError = (e: Event) => {
		if (onError) (onError as (event: Event) => void)(e);
	};
</script>

{#if priority}
	<svelte:head>
		<link
			rel="preload"
			as="image"
			href={resolvedSrc}
			imagesrcset={srcSet}
			imagesizes={resolvedSizes}
			crossorigin={crossOrigin}
		/>
	</svelte:head>
{/if}

{#if fill}
	<span style="position:relative;overflow:hidden;display:block;width:100%;height:100%">
		<img
			{alt}
			src={resolvedSrc}
			srcset={srcSet}
			sizes={resolvedSizes}
			loading={resolvedLoading}
			class={className}
			style={imgStyle}
			crossorigin={crossOrigin}
			referrerpolicy={referrerPolicy}
			fetchpriority={resolvedFetchPriority}
			decoding="async"
			onload={handleLoad}
			onerror={handleError}
		/>
	</span>
{:else}
	<img
		{alt}
		src={resolvedSrc}
		srcset={srcSet}
		sizes={resolvedSizes}
		{width}
		{height}
		loading={resolvedLoading}
		class={className}
		style={imgStyle}
		crossorigin={crossOrigin}
		referrerpolicy={referrerPolicy}
		fetchpriority={resolvedFetchPriority}
		decoding="async"
		onload={handleLoad}
		onerror={handleError}
	/>
{/if}

// src/vue/components/Image.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import type { ImageProps } from '../../../types/image';
import {
	DEFAULT_QUALITY,
	buildOptimizedUrl,
	generateBlurSvg,
	generateSrcSet
} from '../../utils/imageProcessing';

const props = withDefaults(defineProps<ImageProps>(), {
	quality: DEFAULT_QUALITY,
	loading: 'lazy'
});

const blurRemoved = ref(false);

const resolvedSrc = computed(() => {
	if (props.overrideSrc) return props.overrideSrc;
	if (props.unoptimized) return props.src;
	if (props.loader) return props.loader({ src: props.src, width: props.width ?? 0, quality: props.quality });
	if (!props.width) return buildOptimizedUrl(props.src, 0, props.quality);
	return buildOptimizedUrl(props.src, props.width, props.quality);
});

const srcSet = computed(() =>
	props.unoptimized
		? undefined
		: generateSrcSet(props.src, props.width, props.sizes, undefined, props.loader ?? undefined)
);

const resolvedSizes = computed(() => props.sizes ?? (props.fill ? '100vw' : undefined));

const resolvedLoading = computed(() => (props.priority ? 'eager' : props.loading));

const resolvedFetchPriority = computed(() => (props.priority ? 'high' : props.fetchPriority));

const hasBlur = computed(() =>
	props.placeholder === 'blur' ||
	(typeof props.placeholder === 'string' &&
		props.placeholder !== 'empty' &&
		props.placeholder.startsWith('data:'))
);

const blurBackground = computed(() => {
	if (!hasBlur.value || blurRemoved.value) return undefined;
	if (
		typeof props.placeholder === 'string' &&
		props.placeholder !== 'blur' &&
		props.placeholder.startsWith('data:')
	) {
		return generateBlurSvg(props.placeholder);
	}
	if (props.blurDataURL) return generateBlurSvg(props.blurDataURL);
	return undefined;
});

const imgStyle = computed(() => {
	const base: Record<string, string | number> = {
		...(props.style ?? {}),
		color: 'transparent'
	};
	if (blurBackground.value) {
		base.backgroundImage = blurBackground.value;
		base.backgroundSize = 'cover';
		base.backgroundPosition = 'center';
		base.backgroundRepeat = 'no-repeat';
	}
	if (props.fill) {
		base.position = 'absolute';
		base.height = '100%';
		base.width = '100%';
		base.inset = '0';
		base.objectFit = 'cover';
	}
	return base;
});

const handleLoad = (e: Event) => {
	blurRemoved.value = true;
	if (props.onLoad) (props.onLoad as (event: Event) => void)(e);
};

const handleError = (e: Event) => {
	if (props.onError) (props.onError as (event: Event) => void)(e);
};
</script>

<template>
	<Teleport to="head" v-if="priority">
		<link
			rel="preload"
			as="image"
			:href="resolvedSrc"
			:imagesrcset="srcSet"
			:imagesizes="resolvedSizes"
			:crossorigin="crossOrigin"
		/>
	</Teleport>

	<span
		v-if="fill"
		style="position: relative; overflow: hidden; display: block; width: 100%; height: 100%"
	>
		<img
			:alt="alt"
			:src="resolvedSrc"
			:srcset="srcSet"
			:sizes="resolvedSizes"
			:loading="resolvedLoading"
			:class="className"
			:style="imgStyle"
			:crossorigin="crossOrigin"
			:referrerpolicy="referrerPolicy"
			:fetchpriority="resolvedFetchPriority"
			decoding="async"
			@load="handleLoad"
			@error="handleError"
		/>
	</span>

	<img
		v-else
		:alt="alt"
		:src="resolvedSrc"
		:srcset="srcSet"
		:sizes="resolvedSizes"
		:width="width"
		:height="height"
		:loading="resolvedLoading"
		:class="className"
		:style="imgStyle"
		:crossorigin="crossOrigin"
		:referrerpolicy="referrerPolicy"
		:fetchpriority="resolvedFetchPriority"
		decoding="async"
		@load="handleLoad"
		@error="handleError"
	/>
</template>
