// src/angular/components/image.component.ts
import { Component, computed, input, signal } from '@angular/core';
import type { ImageLoader } from '../../../types/image';
import {
	DEFAULT_QUALITY,
	buildOptimizedUrl,
	generateBlurSvg,
	generateSrcSet
} from '../../utils/imageProcessing';

/** Resolve the blur background CSS value from placeholder config */
const resolveBlurBg = (
	placeholderValue: string,
	blurDataUrl: string | undefined
) => {
	if (
		typeof placeholderValue === 'string' &&
		placeholderValue !== 'blur' &&
		placeholderValue.startsWith('data:')
	) {
		return generateBlurSvg(placeholderValue);
	}

	if (blurDataUrl) return generateBlurSvg(blurDataUrl);

	return undefined;
};

@Component({
	selector: 'abs-image',
	standalone: true,
	template: `
		@if (priority()) {
			<link
				rel="preload"
				as="image"
				[attr.href]="resolvedSrc()"
				[attr.imagesrcset]="srcSet()"
				[attr.imagesizes]="resolvedSizes()"
				[attr.crossorigin]="crossOrigin()"
			/>
		}
		@if (fill()) {
			<span style="position:relative;overflow:hidden;display:block;width:100%;height:100%">
				<img
					[alt]="alt()"
					[src]="resolvedSrc()"
					[srcset]="srcSet()"
					[sizes]="resolvedSizes()"
					[loading]="resolvedLoading()"
					[class]="className()"
					[ngStyle]="imgStyle()"
					[crossOrigin]="crossOrigin()"
					[referrerPolicy]="referrerPolicy()"
					[attr.fetchpriority]="resolvedFetchPriority()"
					decoding="async"
					(load)="handleLoad($event)"
					(error)="handleError($event)"
				/>
			</span>
		} @else {
			<img
				[alt]="alt()"
				[src]="resolvedSrc()"
				[srcset]="srcSet()"
				[sizes]="resolvedSizes()"
				[width]="width()"
				[height]="height()"
				[loading]="resolvedLoading()"
				[class]="className()"
				[ngStyle]="imgStyle()"
				[crossOrigin]="crossOrigin()"
				[referrerPolicy]="referrerPolicy()"
				[attr.fetchpriority]="resolvedFetchPriority()"
				decoding="async"
				(load)="handleLoad($event)"
				(error)="handleError($event)"
			/>
		}
	`
})
export class ImageComponent {
	// ── Inputs ──────────────────────────────────────────────────
	readonly alt = input.required<string>();
	readonly blurDataURL = input<string>();
	readonly className = input<string>();
	readonly crossOrigin = input<'anonymous' | 'use-credentials' | ''>();
	readonly fetchPriority = input<'high' | 'low' | 'auto'>();
	readonly fill = input(false);
	readonly height = input<number>();
	readonly loader = input<ImageLoader>();
	readonly loading = input<'lazy' | 'eager'>('lazy');
	readonly onError = input<((event: Event) => void)>();
	readonly onLoad = input<((event: Event) => void)>();
	readonly overrideSrc = input<string>();
	readonly placeholder = input<'blur' | 'empty' | string>('empty');
	readonly priority = input(false);
	readonly quality = input(DEFAULT_QUALITY);
	readonly referrerPolicy = input<string>();
	readonly sizes = input<string>();
	readonly src = input.required<string>();
	readonly style = input<Record<string, string | number>>();
	readonly unoptimized = input(false);
	readonly width = input<number>();

	// ── Internal state ──────────────────────────────────────────
	private readonly blurRemoved = signal(false);

	// ── Computed ────────────────────────────────────────────────
	readonly resolvedSrc = computed(() => {
		const override = this.overrideSrc();

		if (override) return override;

		if (this.unoptimized()) return this.src();

		const loaderFn = this.loader();

		if (loaderFn) return loaderFn({ quality: this.quality(), src: this.src(), width: this.width() ?? 0 });

		const currentWidth = this.width();

		if (!currentWidth) return buildOptimizedUrl(this.src(), 0, this.quality());

		return buildOptimizedUrl(this.src(), currentWidth, this.quality());
	});

	readonly srcSet = computed(() =>
		this.unoptimized()
			? undefined
			: generateSrcSet(this.src(), this.width(), this.sizes(), undefined, this.loader() ?? undefined)
	);

	readonly resolvedSizes = computed(() =>
		this.sizes() ?? (this.fill() ? '100vw' : undefined)
	);

	readonly resolvedLoading = computed(() =>
		this.priority() ? 'eager' as const : this.loading()
	);

	readonly resolvedFetchPriority = computed(() =>
		this.priority() ? 'high' : this.fetchPriority()
	);

	readonly imgStyle = computed(() => {
		const base: Record<string, string | number> = {
			...(this.style() ?? {}),
			color: 'transparent'
		};

		const hasBlur =
			!this.blurRemoved() &&
			(this.placeholder() === 'blur' ||
				(typeof this.placeholder() === 'string' &&
					this.placeholder() !== 'empty' &&
					(this.placeholder() ?? '').startsWith('data:')));

		const blurValue = hasBlur
			? resolveBlurBg(this.placeholder(), this.blurDataURL())
			: undefined;

		if (blurValue) {
			base['background-image'] = blurValue;
			base['background-position'] = 'center';
			base['background-repeat'] = 'no-repeat';
			base['background-size'] = 'cover';
		}

		if (this.fill()) {
			base.height = '100%';
			base.inset = '0';
			base['object-fit'] = 'cover';
			base.position = 'absolute';
			base.width = '100%';
		}

		return base;
	});

	// ── Event handlers ──────────────────────────────────────────
	handleLoad(event: Event) {
		this.blurRemoved.set(true);

		const callback = this.onLoad();

		if (callback) callback(event);
	}

	handleError(event: Event) {
		const callback = this.onError();

		if (callback) callback(event);
	}
}

// src/vue/components/Image.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import type { ImageProps } from '../../../types/image';
import {
	DEFAULT_QUALITY,
	buildOptimizedUrl,
	generateBlurSvg,
	generateSrcSet
} from '../../utils/imageProcessing';

const props = withDefaults(defineProps<ImageProps>(), {
	quality: DEFAULT_QUALITY,
	loading: 'lazy'
});

const blurRemoved = ref(false);

const resolvedSrc = computed(() => {
	if (props.overrideSrc) return props.overrideSrc;
	if (props.unoptimized) return props.src;
	if (props.loader) return props.loader({ src: props.src, width: props.width ?? 0, quality: props.quality });
	if (!props.width) return buildOptimizedUrl(props.src, 0, props.quality);
	return buildOptimizedUrl(props.src, props.width, props.quality);
});

const srcSet = computed(() =>
	props.unoptimized
		? undefined
		: generateSrcSet(props.src, props.width, props.sizes, undefined, props.loader ?? undefined)
);

const resolvedSizes = computed(() => props.sizes ?? (props.fill ? '100vw' : undefined));

const resolvedLoading = computed(() => (props.priority ? 'eager' : props.loading));

const resolvedFetchPriority = computed(() => (props.priority ? 'high' : props.fetchPriority));

const hasBlur = computed(() =>
	props.placeholder === 'blur' ||
	(typeof props.placeholder === 'string' &&
		props.placeholder !== 'empty' &&
		props.placeholder.startsWith('data:'))
);

const blurBackground = computed(() => {
	if (!hasBlur.value || blurRemoved.value) return undefined;
	if (
		typeof props.placeholder === 'string' &&
		props.placeholder !== 'blur' &&
		props.placeholder.startsWith('data:')
	) {
		return generateBlurSvg(props.placeholder);
	}
	if (props.blurDataURL) return generateBlurSvg(props.blurDataURL);
	return undefined;
});

const imgStyle = computed(() => {
	const base: Record<string, string | number> = {
		...(props.style ?? {}),
		color: 'transparent'
	};
	if (blurBackground.value) {
		base.backgroundImage = blurBackground.value;
		base.backgroundSize = 'cover';
		base.backgroundPosition = 'center';
		base.backgroundRepeat = 'no-repeat';
	}
	if (props.fill) {
		base.position = 'absolute';
		base.height = '100%';
		base.width = '100%';
		base.inset = '0';
		base.objectFit = 'cover';
	}
	return base;
});

const handleLoad = (e: Event) => {
	blurRemoved.value = true;
	if (props.onLoad) (props.onLoad as (event: Event) => void)(e);
};

const handleError = (e: Event) => {
	if (props.onError) (props.onError as (event: Event) => void)(e);
};
</script>

<template>
	<Teleport to="head" v-if="priority">
		<link
			rel="preload"
			as="image"
			:href="resolvedSrc"
			:imagesrcset="srcSet"
			:imagesizes="resolvedSizes"
			:crossorigin="crossOrigin"
		/>
	</Teleport>

	<span
		v-if="fill"
		style="position: relative; overflow: hidden; display: block; width: 100%; height: 100%"
	>
		<img
			:alt="alt"
			:src="resolvedSrc"
			:srcset="srcSet"
			:sizes="resolvedSizes"
			:loading="resolvedLoading"
			:class="className"
			:style="imgStyle"
			:crossorigin="crossOrigin"
			:referrerpolicy="referrerPolicy"
			:fetchpriority="resolvedFetchPriority"
			decoding="async"
			@load="handleLoad"
			@error="handleError"
		/>
	</span>

	<img
		v-else
		:alt="alt"
		:src="resolvedSrc"
		:srcset="srcSet"
		:sizes="resolvedSizes"
		:width="width"
		:height="height"
		:loading="resolvedLoading"
		:class="className"
		:style="imgStyle"
		:crossorigin="crossOrigin"
		:referrerpolicy="referrerPolicy"
		:fetchpriority="resolvedFetchPriority"
		decoding="async"
		@load="handleLoad"
		@error="handleError"
	/>
</template>
