// src/react/components/Head.tsx
import type {
	Metadata,
	MetaTag,
	OpenGraph,
	TwitterCard,
	RobotsDirective
} from '../../../types/metadata';

const RobotsContent = ({ robots }: { robots: RobotsDirective }) => {
	const directives: string[] = [];
	if (robots.index === false) directives.push('noindex');
	if (robots.index === true) directives.push('index');
	if (robots.follow === false) directives.push('nofollow');
	if (robots.follow === true) directives.push('follow');
	if (robots.noarchive) directives.push('noarchive');
	if (robots.nosnippet) directives.push('nosnippet');
	if (robots.noimageindex) directives.push('noimageindex');
	if (robots.maxSnippet !== undefined)
		directives.push(`max-snippet:${robots.maxSnippet}`);
	if (robots.maxImagePreview)
		directives.push(`max-image-preview:${robots.maxImagePreview}`);
	if (robots.maxVideoPreview !== undefined)
		directives.push(`max-video-preview:${robots.maxVideoPreview}`);

	const content = directives.join(', ');

	return content ? <meta content={content} name="robots" /> : null;
};

const OpenGraphTags = ({
	openGraph,
	title,
	description
}: {
	openGraph: OpenGraph;
	title: string;
	description: string;
}) => (
	<>
		<meta content={openGraph.title ?? title} property="og:title" />
		<meta
			content={openGraph.description ?? description}
			property="og:description"
		/>
		{openGraph.url && <meta content={openGraph.url} property="og:url" />}
		{openGraph.image && (
			<meta content={openGraph.image} property="og:image" />
		)}
		{openGraph.imageAlt && (
			<meta content={openGraph.imageAlt} property="og:image:alt" />
		)}
		{openGraph.imageWidth && (
			<meta
				content={String(openGraph.imageWidth)}
				property="og:image:width"
			/>
		)}
		{openGraph.imageHeight && (
			<meta
				content={String(openGraph.imageHeight)}
				property="og:image:height"
			/>
		)}
		{openGraph.type && <meta content={openGraph.type} property="og:type" />}
		{openGraph.siteName && (
			<meta content={openGraph.siteName} property="og:site_name" />
		)}
		{openGraph.locale && (
			<meta content={openGraph.locale} property="og:locale" />
		)}
	</>
);

const TwitterTags = ({
	twitter,
	title,
	description
}: {
	twitter: TwitterCard;
	title: string;
	description: string;
}) => (
	<>
		{twitter.card && <meta content={twitter.card} name="twitter:card" />}
		<meta content={twitter.title ?? title} name="twitter:title" />
		<meta
			content={twitter.description ?? description}
			name="twitter:description"
		/>
		{twitter.image && <meta content={twitter.image} name="twitter:image" />}
		{twitter.imageAlt && (
			<meta content={twitter.imageAlt} name="twitter:image:alt" />
		)}
		{twitter.site && <meta content={twitter.site} name="twitter:site" />}
		{twitter.creator && (
			<meta content={twitter.creator} name="twitter:creator" />
		)}
	</>
);

const CustomMetaTag = ({ tag }: { tag: MetaTag }) => {
	if (tag.property)
		return <meta content={tag.content} property={tag.property} />;

	if (tag.httpEquiv)
		return <meta content={tag.content} httpEquiv={tag.httpEquiv} />;

	return <meta content={tag.content} name={tag.name} />;
};

export const Head = ({
	title = 'AbsoluteJS',
	description = 'A page created using AbsoluteJS',
	icon = '/assets/ico/favicon.ico',
	font,
	cssPath,
	canonical,
	openGraph,
	twitter,
	robots,
	meta
}: Metadata = {}) => (
	<head suppressHydrationWarning>
		<meta charSet="utf-8" />
		<title>{title}</title>
		<meta content={description} name="description" />
		<meta content="width=device-width, initial-scale=1" name="viewport" />
		<link href={icon} rel="icon" />
		{canonical && <link href={canonical} rel="canonical" />}
		{openGraph && (
			<OpenGraphTags
				description={description}
				openGraph={openGraph}
				title={title}
			/>
		)}
		{twitter && (
			<TwitterTags
				description={description}
				title={title}
				twitter={twitter}
			/>
		)}
		{robots && <RobotsContent robots={robots} />}
		{meta?.map((tag, i) => <CustomMetaTag key={i} tag={tag} />)}
		{font && (
			<>
				<link href="https://fonts.googleapis.com" rel="preconnect" />
				<link
					crossOrigin="anonymous"
					href="https://fonts.gstatic.com"
					rel="preconnect"
					suppressHydrationWarning
				/>
				<link
					href={`https://fonts.googleapis.com/css2?family=${font}:wght@100..900&display=swap`}
					rel="stylesheet"
					suppressHydrationWarning
				/>
			</>
		)}
		{cssPath &&
			[cssPath]
				.flat()
				.map((path) => (
					<link
						href={path}
						key={path}
						rel="stylesheet"
						suppressHydrationWarning
						type="text/css"
					/>
				))}
	</head>
);

// src/svelte/components/Head.svelte
<script lang="ts">
	import type { Metadata, RobotsDirective } from '../../../types/metadata';

	export let title: Metadata['title'] = 'AbsoluteJS';
	export let description: Metadata['description'] =
		'A page created using AbsoluteJS';
	export let icon: Metadata['icon'] = '/assets/ico/favicon.ico';
	export let font: Metadata['font'] = undefined;
	export let cssPath: Metadata['cssPath'] = undefined;
	export let canonical: Metadata['canonical'] = undefined;
	export let openGraph: Metadata['openGraph'] = undefined;
	export let twitter: Metadata['twitter'] = undefined;
	export let robots: Metadata['robots'] = undefined;
	export let meta: Metadata['meta'] = undefined;

	const robotsContent = (r: RobotsDirective) => {
		const directives: string[] = [];
		if (r.index === false) directives.push('noindex');
		if (r.index === true) directives.push('index');
		if (r.follow === false) directives.push('nofollow');
		if (r.follow === true) directives.push('follow');
		if (r.noarchive) directives.push('noarchive');
		if (r.nosnippet) directives.push('nosnippet');
		if (r.noimageindex) directives.push('noimageindex');
		if (r.maxSnippet !== undefined)
			directives.push(`max-snippet:${r.maxSnippet}`);
		if (r.maxImagePreview)
			directives.push(`max-image-preview:${r.maxImagePreview}`);
		if (r.maxVideoPreview !== undefined)
			directives.push(`max-video-preview:${r.maxVideoPreview}`);
		return directives.join(', ');
	};

	$: cssPaths = cssPath ? (Array.isArray(cssPath) ? cssPath : [cssPath]) : [];
</script>

<svelte:head>
	<meta charset="utf-8" />
	<title>{title}</title>
	<meta name="description" content={description} />
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	<link rel="icon" href={icon} />

	{#if canonical}
		<link rel="canonical" href={canonical} />
	{/if}

	{#if openGraph}
		<meta property="og:title" content={openGraph.title ?? title} />
		<meta
			property="og:description"
			content={openGraph.description ?? description}
		/>
		{#if openGraph.url}
			<meta property="og:url" content={openGraph.url} />
		{/if}
		{#if openGraph.image}
			<meta property="og:image" content={openGraph.image} />
		{/if}
		{#if openGraph.imageAlt}
			<meta property="og:image:alt" content={openGraph.imageAlt} />
		{/if}
		{#if openGraph.imageWidth}
			<meta
				property="og:image:width"
				content={String(openGraph.imageWidth)}
			/>
		{/if}
		{#if openGraph.imageHeight}
			<meta
				property="og:image:height"
				content={String(openGraph.imageHeight)}
			/>
		{/if}
		{#if openGraph.type}
			<meta property="og:type" content={openGraph.type} />
		{/if}
		{#if openGraph.siteName}
			<meta property="og:site_name" content={openGraph.siteName} />
		{/if}
		{#if openGraph.locale}
			<meta property="og:locale" content={openGraph.locale} />
		{/if}
	{/if}

	{#if twitter}
		{#if twitter.card}
			<meta name="twitter:card" content={twitter.card} />
		{/if}
		<meta name="twitter:title" content={twitter.title ?? title} />
		<meta
			name="twitter:description"
			content={twitter.description ?? description}
		/>
		{#if twitter.image}
			<meta name="twitter:image" content={twitter.image} />
		{/if}
		{#if twitter.imageAlt}
			<meta name="twitter:image:alt" content={twitter.imageAlt} />
		{/if}
		{#if twitter.site}
			<meta name="twitter:site" content={twitter.site} />
		{/if}
		{#if twitter.creator}
			<meta name="twitter:creator" content={twitter.creator} />
		{/if}
	{/if}

	{#if robots}
		{@const content = robotsContent(robots)}
		{#if content}
			<meta name="robots" {content} />
		{/if}
	{/if}

	{#if meta}
		{#each meta as tag}
			{#if tag.property}
				<meta property={tag.property} content={tag.content} />
			{:else if tag.httpEquiv}
				<meta http-equiv={tag.httpEquiv} content={tag.content} />
			{:else if tag.name}
				<meta name={tag.name} content={tag.content} />
			{/if}
		{/each}
	{/if}

	{#if font}
		<link rel="preconnect" href="https://fonts.googleapis.com" />
		<link
			rel="preconnect"
			href="https://fonts.gstatic.com"
			crossorigin="anonymous"
		/>
		<link
			href={`https://fonts.googleapis.com/css2?family=${font}:wght@100..900&display=swap`}
			rel="stylesheet"
		/>
	{/if}

	{#each cssPaths as path}
		<link rel="stylesheet" href={path} type="text/css" />
	{/each}
</svelte:head>
