// src/svelte/components/Image.svelte
<script lang="ts">
	import type { ImageProps } from '../../../types/image';
	import {
		DEFAULT_QUALITY,
		buildOptimizedUrl,
		generateBlurSvg,
		generateSrcSet
	} from '../../utils/imageProcessing';

	let {
		src,
		alt,
		width,
		height,
		fill,
		quality = DEFAULT_QUALITY,
		sizes,
		loader,
		unoptimized,
		loading,
		priority,
		placeholder,
		blurDataURL,
		className,
		style,
		onLoad,
		onError,
		crossOrigin,
		referrerPolicy,
		fetchPriority,
		overrideSrc
	}: ImageProps = $props();

	const resolvedSrc = $derived.by(() => {
		if (overrideSrc) return overrideSrc;
		if (unoptimized) return src;
		if (loader) return loader({ src, width: width ?? 0, quality });
		if (!width) return buildOptimizedUrl(src, 0, quality);
		return buildOptimizedUrl(src, width, quality);
	});

	const srcSet = $derived(
		unoptimized
			? undefined
			: generateSrcSet(src, width, sizes, undefined, loader ?? undefined)
	);

	const resolvedSizes = $derived(sizes ?? (fill ? '100vw' : undefined));

	const resolvedLoading = $derived(priority ? 'eager' : (loading ?? 'lazy'));

	const resolvedFetchPriority = $derived(priority ? 'high' : fetchPriority);

	const hasBlur = $derived(
		placeholder === 'blur' ||
			(typeof placeholder === 'string' &&
				placeholder !== 'empty' &&
				placeholder.startsWith('data:'))
	);

	const blurBackground = $derived.by(() => {
		if (!hasBlur) return undefined;
		if (
			typeof placeholder === 'string' &&
			placeholder !== 'blur' &&
			placeholder.startsWith('data:')
		) {
			return generateBlurSvg(placeholder);
		}
		if (blurDataURL) return generateBlurSvg(blurDataURL);
		return undefined;
	});

	const imgStyle = $derived.by(() => {
		const base: Record<string, string | number> = {
			...(style ?? {}),
			color: 'transparent'
		};
		if (blurBackground) {
			base.backgroundImage = blurBackground;
			base.backgroundSize = 'cover';
			base.backgroundPosition = 'center';
			base.backgroundRepeat = 'no-repeat';
		}
		if (fill) {
			base.position = 'absolute';
			base.height = '100%';
			base.width = '100%';
			base.inset = 0;
			base.objectFit = 'cover';
		}
		return Object.entries(base)
			.map(([k, v]) => `${k.replace(/[A-Z]/g, (m) => `-${m.toLowerCase()}`)}:${v}`)
			.join(';');
	});

	const handleLoad = (e: Event) => {
		if (blurBackground) {
			(e.target as HTMLImageElement).style.backgroundImage = 'none';
		}
		if (onLoad) (onLoad as (event: Event) => void)(e);
	};

	const handleError = (e: Event) => {
		if (onError) (onError as (event: Event) => void)(e);
	};
</script>

{#if priority}
	<svelte:head>
		<link
			rel="preload"
			as="image"
			href={resolvedSrc}
			imagesrcset={srcSet}
			imagesizes={resolvedSizes}
			crossorigin={crossOrigin}
		/>
	</svelte:head>
{/if}

{#if fill}
	<span style="position:relative;overflow:hidden;display:block;width:100%;height:100%">
		<img
			{alt}
			src={resolvedSrc}
			srcset={srcSet}
			sizes={resolvedSizes}
			loading={resolvedLoading}
			class={className}
			style={imgStyle}
			crossorigin={crossOrigin}
			referrerpolicy={referrerPolicy}
			fetchpriority={resolvedFetchPriority}
			decoding="async"
			onload={handleLoad}
			onerror={handleError}
		/>
	</span>
{:else}
	<img
		{alt}
		src={resolvedSrc}
		srcset={srcSet}
		sizes={resolvedSizes}
		{width}
		{height}
		loading={resolvedLoading}
		class={className}
		style={imgStyle}
		crossorigin={crossOrigin}
		referrerpolicy={referrerPolicy}
		fetchpriority={resolvedFetchPriority}
		decoding="async"
		onload={handleLoad}
		onerror={handleError}
	/>
{/if}

// src/react/components/Image.tsx
import type { ImageProps } from '../../../types/image';
import {
	DEFAULT_QUALITY,
	buildOptimizedUrl,
	generateBlurSvg,
	generateSrcSet
} from '../../utils/imageProcessing';

const resolveSource = (
	src: string,
	overrideSrc: ImageProps['overrideSrc'],
	unoptimized: ImageProps['unoptimized'],
	loader: ImageProps['loader'],
	width: ImageProps['width'],
	quality: number
) => {
	if (overrideSrc) return overrideSrc;
	if (unoptimized) return src;
	if (loader) return loader({ quality, src, width: width ?? 0 });
	if (!width) return buildOptimizedUrl(src, 0, quality);

	return buildOptimizedUrl(src, width, quality);
};

const resolveBlurBackground = (
	hasBlur: boolean,
	placeholder: ImageProps['placeholder'],
	blurDataURL: ImageProps['blurDataURL']
) => {
	if (!hasBlur) return undefined;

	if (
		typeof placeholder === 'string' &&
		placeholder !== 'blur' &&
		placeholder.startsWith('data:')
	) {
		return generateBlurSvg(placeholder);
	}

	if (blurDataURL) return generateBlurSvg(blurDataURL);

	return undefined;
};

export const Image = ({
	alt,
	blurDataURL,
	className,
	crossOrigin,
	fetchPriority,
	fill,
	height,
	loader,
	loading,
	onError,
	onLoad,
	overrideSrc,
	placeholder,
	priority,
	quality = DEFAULT_QUALITY,
	referrerPolicy,
	sizes,
	src,
	style,
	unoptimized,
	width
}: ImageProps) => {
	// ── Resolve src ─────────────────────────────────────────────
	const resolvedSrc = resolveSource(src, overrideSrc, unoptimized, loader, width, quality);

	// ── srcSet ──────────────────────────────────────────────────
	const srcSet = unoptimized
		? undefined
		: generateSrcSet(src, width, sizes, undefined, loader ?? undefined);

	// ── Sizes ───────────────────────────────────────────────────
	const resolvedSizes = sizes ?? (fill ? '100vw' : undefined);

	// ── Loading behavior ────────────────────────────────────────
	const resolvedLoading = priority ? 'eager' : (loading ?? 'lazy');
	const resolvedFetchPriority = priority ? 'high' : fetchPriority;

	// ── Blur placeholder ────────────────────────────────────────
	const hasBlur =
		placeholder === 'blur' ||
		(typeof placeholder === 'string' &&
			placeholder !== 'empty' &&
			placeholder.startsWith('data:'));

	const blurBackground = resolveBlurBackground(hasBlur, placeholder, blurDataURL);

	// ── Styles ──────────────────────────────────────────────────
	const imgStyle: Record<string, string | number> = {
		...(style ?? {}),
		...(blurBackground
			? {
					backgroundImage: blurBackground,
					backgroundPosition: 'center',
					backgroundRepeat: 'no-repeat',
					backgroundSize: 'cover'
				}
			: {}),
		...(fill
			? {
					color: 'transparent',
					height: '100%',
					inset: 0,
					objectFit: 'cover',
					position: 'absolute',
					width: '100%'
				}
			: { color: 'transparent' })
	};

	// ── Preload link for priority images ────────────────────────
	const preloadLink = priority ? (
		<link
			as="image"
			crossOrigin={crossOrigin}
			href={resolvedSrc}
			imageSizes={resolvedSizes}
			imageSrcSet={srcSet}
			rel="preload"
		/>
	) : null;

	// ── Fill mode wrapper ───────────────────────────────────────
	const imgElement = (
		<img
			alt={alt}
			className={className}
			crossOrigin={crossOrigin}
			decoding="async"
			fetchPriority={resolvedFetchPriority}
			height={fill ? undefined : height}
			loading={resolvedLoading}
			onError={onError ? (event) => onError(event.nativeEvent) : undefined}
			onLoad={(event) => {
				const { target } = event;

				if (blurBackground && target instanceof HTMLImageElement) {
					target.style.backgroundImage = 'none';
				}

				if (onLoad) onLoad(event.nativeEvent);
			}}
			referrerPolicy={referrerPolicy}
			sizes={resolvedSizes}
			src={resolvedSrc}
			srcSet={srcSet}
			style={imgStyle}
			width={fill ? undefined : width}
		/>
	);

	if (fill) {
		return (
			<>
				{preloadLink}
				<span
					style={{
						display: 'block',
						height: '100%',
						overflow: 'hidden',
						position: 'relative',
						width: '100%'
					}}
				>
					{imgElement}
				</span>
			</>
		);
	}

	return (
		<>
			{preloadLink}
			{imgElement}
		</>
	);
};
